name: Test Docker image build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches-ignore:
      - master

jobs:
  build_docker_test:
    name: Test Docker image build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ no, sv, da, fi, nl ]

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Check out the repo
        uses: actions/checkout@v7

      - name: Cache game iso
        uses: actions/cache@v6
        id: iso
        with:
          path: iso/mullebil_${{ matrix.language }}.iso
          key: game-iso-${{ matrix.language }}-${{ hashFiles('iso/mullebil_*.iso') }}
          restore-keys: game-iso-${{ matrix.language }}-

      - name: Download game
        run: python build_scripts/build.py ${{ matrix.language }} download-only

      - name: Build Docker image
        id: push
        uses: docker/build-push-action@v7
        with:
          push: false
          build-contexts: iso=iso
          build-args: |
            GAME_LANG=${{ matrix.language }}
            OPTIPNG_LEVEL=0
